name: fleet_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.2.0
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  dio: ^5.9.0
  drift: ^2.30.1
  easy_localization: ^3.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_compass: ^0.8.1
  flutter_foreground_task: ^9.2.0
  flutter_form_builder: ^10.2.0
  flutter_map: ^8.2.2
  flutter_map_animations: ^0.9.0
  flutter_secure_storage: ^10.0.0
  form_builder_validators: ^11.2.0
  freezed_annotation: ^3.1.0
  geolocator: ^14.0.2
  get_it: ^9.2.0
  go_router: ^17.0.1
  google_fonts: ^7.0.2
  hydrated_bloc: ^10.1.1
  json_annotation: ^4.9.0
  json_serializable: ^6.11.4
  latlong2: ^0.9.1
  marionette_flutter: ^0.2.4
  path: ^1.9.1
  path_provider: ^2.1.5
  retrofit: ^4.9.2
  retrofit_generator: ^10.2.1
  share_plus: ^12.0.1
  shared_preferences: ^2.5.4
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.41
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.5
  freezed: ^3.2.4
  drift_dev: ^2.30.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
